/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "two-factor.login": [],
    "two-factor.login.store": [],
    "two-factor.enable": [],
    "two-factor.confirm": [],
    "two-factor.disable": [],
    "two-factor.qr-code": [],
    "two-factor.secret-key": [],
    "two-factor.recovery-codes": [],
    "two-factor.regenerate-recovery-codes": [],
    "sanctum.csrf-cookie": [],
    "home": [],
    "shop": [],
    "productItem": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "confidentialite": [],
    "about": [],
    "portfolio": [],
    "workshops": [],
    "workshop": [
        {
            "name": "workshop",
            "required": true,
            "binding": "id"
        }
    ],
    "cart": [],
    "verify-account": [],
    "mentions": [],
    "api.products.delete": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        }
    ],
    "api.products.deleteMedia": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "api.products.highlightImage": [
        {
            "name": "product",
            "required": true,
            "binding": "id"
        },
        {
            "name": "media",
            "required": true,
            "binding": "id"
        }
    ],
    "api.categories.delete": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "api.options.delete": [
        {
            "name": "option",
            "required": true,
            "binding": "id"
        }
    ],
    "register": [],
    "register.store": [],
    "admin.product.index": [],
    "admin.product.store": [],
    "admin.categories.index": [],
    "admin.categories.store": [],
    "admin.options.index": [],
    "admin.options.store": [],
    "admin.workshops.index": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
