name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  build-image-api:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Connexion à GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: NWB-H
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: api
          push: true
          tags: |
            ghcr.io/nwb-h/windigo-serigraphie-projet-api:latest
            ghcr.io/nwb-h/windigo-serigraphie-projet-api:${{ github.sha }}

  build-image-spa:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Connexion à GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: NWB-H
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: spa
          push: true
          tags: |
            ghcr.io/nwb-h/windigo-serigraphie-projet-spa:latest
            ghcr.io/nwb-h/windigo-serigraphie-projet-spa:${{ github.sha }}

  ftpO2switch:
    runs-on: ubuntu-latest
    needs:
      - build-image-spa
      - build-image-api
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Build frontend Vue.js
      - name: Build frontend
        working-directory: ./spa
        run: |
          npm install
          npm run build

      # 4️⃣ Vérifier que le dossier dist existe
      - name: Ensure dist exists
        run: |
          if [ ! -d "./spa/dist" ]; then
            echo "Error: ./spa/dist not found!"
            exit 1
          fi

      # 5️⃣ Déployer frontend via FTP
      - name: Upload frontend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./spa/dist/
          server-dir: /windigoprint-frontend.fohu7030.odns.fr/
          dangerous-clean-slate: true

      # 6️⃣ Déployer backend Laravel via FTP
      - name: Upload backend via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./api/
          server-dir: /windigoprint-backend.fohu7030.odns.fr/Windigo-Serigraphie-projet-main/api/
          dangerous-clean-slate: true