name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  build-image-api:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Connexion à GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: NWB-H
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: api
          push: true
          tags: |
            ghcr.io/nwb-h/windigo-serigraphie-projet-api:latest
            ghcr.io/nwb-h/windigo-serigraphie-projet-api:${{ github.sha }}

  build-image-spa:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Connexion à GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: NWB-H
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: spa
          push: true
          tags: |
            ghcr.io/nwb-h/windigo-serigraphie-projet-spa:latest
            ghcr.io/nwb-h/windigo-serigraphie-projet-spa:${{ github.sha }}

  ftptO2switch:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js pour builder le frontend
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3️⃣ Build frontend Vue.js
      - name: Build frontend
        working-directory: ./spa
        run: |
          npm install
          npm run build

      # 4️⃣ Déployer frontend via FTP (seulement fichiers modifiés)
      - name: Upload frontend (dist) via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./spa/dist
          server-dir: /www
          git-ftp-args: --insecure --syncroot ./spa/dist

      # 5️⃣ Déployer backend Laravel via FTP (seulement fichiers modifiés)
      - name: Upload backend (Laravel) via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SERVER }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local-dir: ./api
          server-dir: /api
          git-ftp-args: --insecure --syncroot ./api